gui:
  theme:
    activeBorderColor:
      - "#61afef"
      - bold
    inactiveBorderColor:
      - "#545862"
    searchingActiveBorderColor:
      - "#d19a66"
    optionsTextColor:
      - "#61afef"
    selectedLineBgColor:
      - "#3e4451"
    cherryPickedCommitBgColor:
      - "#545862"
    cherryPickedCommitFgColor:
      - "#61afef"
    markedBaseCommitFgColor:
      - "#61afef"
    unstagedChangesColor:
      - "#e06c75"
    defaultFgColor:
      - "#abb2bf"
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme TwoDark -s
