gui:
  theme:
    activeBorderColor:
      - "#61afef" # Blue for active borders
      - bold
    inactiveBorderColor:
      - "#3e4451" # Darker shade for inactive borders
    optionsTextColor:
      - "#56b6c2" # Cyan for options text
    selectedLineBgColor:
      - "#3e4451" # Dark background for selected lines
    selectedRangeBgColor:
      - "#3e4451"
    cherryPickedCommitBgColor:
      - "#98c379" # Green background for cherry-picked commits
    cherryPickedCommitFgColor:
      - "#282c34" # Dark foreground for contrast
    unstagedChangesColor:
      - "#e06c75" # Red for unstaged changes
    defaultFgColor:
      - "#abb2bf" # Foreground text color
    searchingActiveBorderColor:
      - "#c678dd" # Magenta for active search
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme TwoDark -s
#
# Use the mocha catppuccin theme with blue accent
# theme:
#   activeBorderColor:
#     - "#89b4fa"
#     - bold
#   inactiveBorderColor:
#     - "#a6adc8"
#   optionsTextColor:
#     - "#89b4fa"
#   selectedLineBgColor:
#     - "#313244"
#   cherryPickedCommitBgColor:
#     - "#45475a"
#   cherryPickedCommitFgColor:
#     - "#89b4fa"
#   unstagedChangesColor:
#     - "#f38ba8"
#   defaultFgColor:
#     - "#cdd6f4"
#   searchingActiveBorderColor:
#     - "#f9e2af"
